# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_1 <- function(X, X0, y) {
    .Call(`_assignment1knn_knn_1`, X, X0, y)
}

knn_more <- function(X, X0, y, K) {
    .Call(`_assignment1knn_knn_more`, X, X0, y, K)
}

knn_inv <- function(X, X0, y, K) {
    .Call(`_assignment1knn_knn_inv`, X, X0, y, K)
}

